const STACK = 100000;
const INITIAL_AMOUNT = 1;
const MAX_AMOUNT = 100;
const REPETITION_BEFORE = 4;
const NB_LAUNCH = 100000;

module.exports = {
  STACK,
  INITIAL_AMOUNT,
  MAX_AMOUNT,
  REPETITION_BEFORE,
  NB_LAUNCH
};
